### ISSUE TITLE
How to detect that status and timestamp is writable (Mantis 2866)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#10]
Currently there is no way to detect if a server supports writing of status and or timestamp.

One option would be to have a server wide capability information about general support of this feature.

A more specific information would be to extend the access level with additional flags for StatusWrite and TimestampWrite.

**Comment by jouniaro** [comment]
The original reference is to Mantis 2600, https://opcfoundation-onlineapplications.org/mantis/view.php?id=2600

**Comment by jouniaro** [comment]
Specification 1.03 defines new bits for StatusWrite and TimestampWrite

**Comment by jouniaro** [comment]
Closing this as a duplicate of the new task #52 (which describes it better)
