### ISSUE TITLE
Error In Client HA ReadService-HistoryReadDetails Extension Object requires converting  ReadRawModifiedDetails to an byteArray object , when I do the same we get an error

### ISSUE THREAD

**Issue by chandru9050** [OPCFoundation/UA-Java#100]
In Client HA ReadService-HistoryReadDetails Extension Object requires converting  ReadRawModifiedDetails  object to an byteArray object , when I do convert ReadRawModifiedDetails  object to byte array we get an serialization error. Please let me know how do i convert  ReadRawModifiedDetails  object to an ByteArray . 
 
See this below constructor it expects a byte[] object 
ExtensionObject(ExpandedNodeId typeId, byte[] object)

**Comment by jouniaro** [comment]
You should use 'ExtensionObject.binaryEncode(details, encoderContext)' to encode the parameter, where encoderContext can be found from the Application object used in the client (e.g. myApplication in the SampleClient)
