### ISSUE TITLE
Can not compile on my JDK 8

### ISSUE THREAD

**Issue by irwantantu** [OPCFoundation/UA-Java#105]
Hi all,
I downloaded the latest one and try to compile it by mvn package, it gives me a lot error.. Anybody experience this? Any suggestion?
I am using JDK 8

**Comment by bjakke** [comment]
Please list: 
* The complete error message you got
* Your java version ("JDK 8" is not enough, please output java -version, also which provider, e.g. oracle, openjdk, other?)
* Your operating system
* Exact mvn command you used

Also if binaries are enough, to avoid most of these problems I attached binaries for 1.03.342.0 in the releases (https://github.com/OPCFoundation/UA-Java/releases/tag/1.03.342.0).

**Comment by irwantantu** [comment]
Got it to work... thanks..
