### ISSUE TITLE
Subject class type invalid

### ISSUE THREAD

**Issue by laica10** [OPCFoundation/UA-Java#114]
Hey I keep getting this error (0x80010000) which tells me "Subject class type invalid". I'm just using the default ExampleKeys class and still it crashes when creating the http cert, the other 2 work as they should...

I really need a quick fix and I'm not experienced with OPC at all..

Kind regards,
Jarno Gabriel

**Comment by jouniaro** [comment]
Which CryptoProvider are you using, i.e. which security libraries have you linked to your project (see the project [readme description](https://github.com/OPCFoundation/UA-Java/blob/master/README.md))?

**Comment by laica10** [comment]
I'm using BouncyCastle.. But it only seems to work in the IDE (to generate the certifications) whenever I build the project it doesn't generate the certifications anymore but I'm currently using the certifications generated by the project in the IDE whenever I try to run it on my desktop or the .jar in generally

**Comment by jouniaro** [comment]
Any more information. A stack trace, for example?

**Comment by jouniaro** [comment]
If this is your issue (https://stackoverflow.com/questions/48157470/opcua-gethttpscert-error) , the stack trace (https://imgur.com/a/BZ5qh) is actually referring to SunJceCryptoProvider. It seems there is an issue with that one, crating the certificate.

Add this line to the beginning of main(), to ensure the Bouncy Castle is available and in use:

`CryptoUtil.setCryptoProvider(new BcCryptoProvider());`

**Comment by laica10** [comment]
Fun fact: this is actually my stack voerflow question.. and my stack trace..

**Comment by jouniaro** [comment]
Yes, that's what I figured...

**Comment by laica10** [comment]
There u go, this was just taken from my console: 
https://imgur.com/a/vLWAA

**Comment by jouniaro** [comment]
What's your Java environment?

**Comment by laica10** [comment]
I'm using eclipse (IDE) Java 1.8.0_131 JDK

**Comment by jouniaro** [comment]
In which platform?

**Comment by laica10** [comment]
Mac, also doesn't work on Windows..

**Comment by jouniaro** [comment]
A quick search gives this: https://github.com/bcgit/bc-java/issues/156

Which looks like Bouncy Castle is still not properly used. So, please add

Security.addProvider(new BouncyCastleProvider())

to the beginning of your code as well.

I am not sure why it doesn't pick Bouncy Castle for you automatically. Have you perhaps modified the java.security static registration file?

**Comment by jouniaro** [comment]
And, don't package the Bouncy Castle libs to your application JAR, if you make one. They are signed and cannot be repackaged.

**Comment by laica10** [comment]
I already did the Security one from the beginning I'll try adding the CryptoUtil one too

**Comment by laica10** [comment]
Sorry for the late response, I've been really busy.
I'm still getting the same error with the `CryptoUtil.setCryptoProvider(new BcCryptoProvider());` added in the static method of the main class..

**Comment by jouniaro** [comment]
Do you still see that DefaultJcaJceHelper in the stack trace?

**Comment by laica10** [comment]
Yep sure do, identical stack trace..

**Comment by jouniaro** [comment]
Please, enable DEBUG level logging (log4j.properties in resources of examples project for example) and show what your app outputs for available providers. E.g.

DEBUG [main] org.opcfoundation.ua.utils.CryptoUtil     - Providers=[SUN version 1.8, SunRsaSign version 1.8, SunEC version 1.8, SunJSSE version 1.8, SunJCE version 1.8, ...]

OTOH, you can always decide to store the private keys without password in your app or even disable HTTPS; it is an optional transport protocol anyway.

**Comment by laica10** [comment]
Still doesn't work it doesn't even show me the debug..
I think I'm just going to deliver the certificates with the app bundled.

**Comment by jouniaro** [comment]
Closing the issue which did not get further progress
