### ISSUE TITLE
Is SessionChannel Thread Safe?

### ISSUE THREAD

**Issue by amitavabasu** [OPCFoundation/UA-Java#117]
Greetings All,

I am new to OPC-UA and OPC-UA Java SDK, and this is not an issue I am reporting, rather I just have a quick question if anyone can help. I could not find a suitable forum to ask this. If you have a forum for questions please direct me to that.

I am trying to create a standalone Java app which needs to go and query multiple nodes from a OPC-UA server, periodically. My plan to create a SessionChannelManager and keep only one instance of activated SessionChannel. Is it safe to distribute this SessionChannel to multiple threads. Each thread periodically request an activated SessionChannel from the Manager, use Browse() or Read() method. If SessionChannel is not thread safe, I have to create a pool or something like that (more like JDBC connection pooling), if they are thread safe, I can just issue a single instance of SessionChannel to any number of threads. I presume SessionChannel is a heavy-weight object and always better to keep their numbers limited. Let me know if you have any advice for me.

Thanks in Advance
AB

**Comment by jouniaro** [comment]
Yes, the SessionChannel is safe to use for sending service requests simultaneously from different threads. 

But activation and closing the session are not thread safe.
