### ISSUE TITLE
NamespaceUri is always defined for ExpandedNodeId objects of NamespaceIndex=0: breaks interoperability (Mantis 2821)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#12]
This is hard coded, to make the XML serialiser to work with the standard types. However, it breaks interoperability since the references are now referring to the nodes with NamespaceUri, especially for the standard nodes. But for those it is least necessary to define the Uri since that is a constant value.

This was changed in the latest stack.

**Comment by jouniaro** [comment]
Does not break interoperability in practice after all (did with one implementation maybe). This perhaps causes some performance issues, so should be checked anyway.
