### ISSUE TITLE
Bad_SessionIdInvalid bug?

### ISSUE THREAD

**Issue by OscarLixiaozhou** [OPCFoundation/UA-Java#124]
When I use  client sample("Client Example1")to visit "Nano Server" ,occur a error (Exception in thread "main" ServiceFault: Bad_SessionIdInvalid (0x80250000) "The session id is not valid.").I use another demo server from Unified Automation to test client also ouccur the same error,the error is occured when client try to use read service.(   `ReadResponse res = myChannel.Read(req);`  ).
 
![badsessionidinvalid](https://user-images.githubusercontent.com/35477926/35519750-19d32b44-0550-11e8-804e-073c3dc7851e.png)

**Comment by jouniaro** [comment]
Looks like this example is incomplete as it does not activate the session before making the read call.

Please, check the SampleClient, which is a better example.

Or you can fix the ClientExample by replacing myChannel with mySession as follows:

`    //////////// TEST-STACK ////////////
    // Create Channel
    // ServiceChannel myChannel = myClient.createServiceChannel(endpoint);
    SessionChannel mySession = myClient.createSessionChannel(url);
    // mySession.activate("username", "123");
    mySession.activate();

    // Create Test Request
    ReadValueId[] nodesToRead = {new ReadValueId(Identifiers.RootFolder, Attributes.BrowseName, null, null)};
    ReadRequest req = new ReadRequest(null, 0.0, TimestampsToReturn.Both, nodesToRead);
    System.out.println("REQUEST: " + req);

    // Invoke service
    ReadResponse res = mySession.Read(req);
    // Print result
    System.out.println("RESPONSE: " + res);
    //////////////////////////////////////


    ///////////// SHUTDOWN /////////////
    // Close channel
    mySession.closeAsync();`

**Comment by OscarLixiaozhou** [comment]
I revise the  code as  you metioned,the problem has resovled .Thanks,jouniaro
