### ISSUE TITLE
Read DataType Attribute

### ISSUE THREAD

**Issue by marracash** [OPCFoundation/UA-Java#128]
I would navigate the OPC-UA server address space in order to extract information about all the node attributes. The variable (node type variable) has several attributes (i.e., Datatype, AccessLevel, etc.) but I can extract only nodeId, browseName and nodeClass via ReferenceDescription class. 

My scenario.

- I have a variable nodeId String. How I can read the DataType attribute?

Thanks in advance

**Comment by jouniaro** [comment]
You have to make a ReadRequest for the DataType attribute
