### ISSUE TITLE
Server socket goes to unrecoverable CLOSE_WAIT state (Mantis 3158)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#13]
Under heavy load and a lot of failing connection attempts, especially, but also sometimes in normal operation, the server socket blocks so that no more connections are available from client applications.

The symptom is that the new connection attempts also stay in the CLOSE_WAIT state in 'netstat' listing.

The problem is reproducible in Linux operating systems and requires heavy load and failing connection attempts to reveal itself with a higher probability.

Since the socket gets blocked no more connections are available and this is a severe issue for the applications.

--> related to Mantis 3117

**Comment by jouniaro** [comment]
Have not got reports for this lately, assuming there is no reason to keep this open any more.
