### ISSUE TITLE
Cannot able to register the OPC server to LDS

### ISSUE THREAD

**Issue by m-kavinraj** [OPCFoundation/UA-Java#147]
I am new to OPC UA stack, I need to connect the OPC stack server with LabVIEW. For which I need to register the server as a registered one in Global Discovery server.

**Comment by htahvanainen** [comment]
Hi,

The OPC UA Java Stack only implements the communication protocol. That is messaging and security. Implementing Discovery Services will require application level development and it's not covered by the plain stack.

Please see these previous issues which explain the matter:
#142
#62
#88 

For more details about OPC UA specification, please see https://opcfoundation.org/developer-tools/specifications-unified-architecture

The specification part 12 provides an in-depth explanation about Discovery Services.
