### ISSUE TITLE
TcpConnection$ReadThread.run does not catch all Exceptions

### ISSUE THREAD

**Issue by htahvanainen** [OPCFoundation/UA-Java#18]
With misbehaving server applications, ReadThread should handle Exceptions in more robust way.

> Exception in thread “TcpConnection/Read” java.lang.IllegalArgumentException: Variant cannot be org.opcfoundation.ua.builtintypes.Variant
> at org.opcfoundation.ua.builtintypes.Variant.(Unknown Source)
> at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getVariant(Unknown Source)
> at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getDataValue(Unknown Source)
> at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getDataValueArray(Unknown Source)
> at org.opcfoundation.ua.core.EncodeableSerializer$121.getEncodeable(Unknown Source)
> at org.opcfoundation.ua.encoding.utils.AbstractSerializer.getEncodeable(Unknown Source)
> at org.opcfoundation.ua.encoding.utils.SerializerComposition.getEncodeable(Unknown Source)
> at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getMessage(Unknown Source)
> at org.opcfoundation.ua.transport.tcp.io.TcpConnection$ReadThread.run(Unknown Source)

Original forum post: [http://forum.prosysopc.com/forum/opc-ua-java-sdk/tcpconnectionread-java-lang-illegalargumentexception/](http://forum.prosysopc.com/forum/opc-ua-java-sdk/tcpconnectionread-java-lang-illegalargumentexception/)

**Comment by bjakke** [comment]
Fixed in referenced commit, the ReadThread now does catch Exception in addition of the existing ones. In this case an error is logged and new ServiceResultException(StatusCodes.Bad_InternalError, e) is put to the closeError. There is not much else that can be done other than closing the channel in this case.
