### ISSUE TITLE
Private key storage on Android private storage fails (Mantis 2337)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#21]
The PrivKey can be stored in PEM format on the sdcard (ExternalStorage), but not in the internal storage. Reading it from there fails for some reason.

It would be safer to store the private key in the internal memory which only the application can access itself.

**Comment by jouniaro** [comment]
Strong the key seems to work on the latest Android versions, but now the PrivateKey is loaded in a format that cannot be used to sign asymmetric messages leading to errors in ScCryptoProvider.signAsymm. Needs to be checked why the PrivateKey is not of a usable instance and how to make it compatible again. This is possibly a change in the recent Android versions.

**Comment by jouniaro** [comment]
This is not a real problem any more, so will close.
