### ISSUE TITLE
Stack Should Support Certificate Validation (Mantis 2191)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#22]
The ANSI C and .NET stacks include code to validate certificates. This is a fundamental feature that should be part of the stack.

The feature should be implemented using the Java CertPath architecture
http://download.java.net/jdk8/docs/technotes/guides/security/certpath/CertPathProgGuide.html [^]

**Comment by bjakke** [comment]
Done in referenced commit. See new classes in org.opcfoundation.ua.cert packages, important ones are CertificateStore, which is an interface describing a certificate store; DefaultCertificateValidator which is an implementation of CertificateValidator that uses a CertificateStore to query the certificates; PkiDirectoryCertificateStore which uses a PKI folder structure to store the certificates.
