### ISSUE TITLE
Implement update of Certificate Validation Steps in Part 4 (Mantis 2681)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#23]
The rule to stop certificate checks if a trusted certificate is found was removed since trusted CA certificates may be revoked by their issuers and therefore a full check of the certificate chain is required.

The certificate validation steps in Table 101 got reordered to first check Certificate Structure, Signature and Trust List. If one of the tree checks fails the unspecific status Bad_SecurityChecksFailed is returned. It the certificate is trusted, the remaining checks will return the specific error like defined in V1.02.

The first change should be already implemented since it reflects the certificate check test case matrix developed in the SMG.

But the changes in the Certificate Validation Step error handling (return of right error) must be applied to the stack.

Part 4 spec change see Mantis 2534
Compliance test update see Mantis 2496.

**Comment by jouniaro** [comment]
Depends on #22
