### ISSUE TITLE
Verify / follow improved rules for multi dimensional arrays (Mantis 2819/2861)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#53]
Additional rule for Variant decoding in UA Part 6:
"If ArrayDimensions are inconsistent with the ArrayLength then the decoder shall stop and raise a Bad_DecodingError"

**Comment by bjakke** [comment]
Fixed in referenced commit. BinaryDecoder.getVariant does now check total size based on array dimensions
