### ISSUE TITLE
how can i use monitor

### ISSUE THREAD

**Issue by levonhe** [OPCFoundation/UA-Java#59]
How can i create a monitor to recevie server port information from client?

**Comment by nathanpocock** [comment]
I think you want to call GetEndpoints to retrieve "server port information"? (your question is a little vague)

You won't be able to "monitor" this information, you will need to periodically fetch it using a timer, for example.

Please use the OPC Foundation [forum](https://opcfoundation.org/forum/)  for this type of question. The "issues" tab is reporting problems or requesting new features etc.

**Comment by levonhe** [comment]
ok.
