### ISSUE TITLE
HTTP libraries should be updated to the latest versions (Mantis 3049)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#6]
The stack is currently using Apache HTTP Core libraries that are 2 years old (v4.2.4/5). These should be updated to the latest (v4.4.1). The stack cannot currently be used with the latest versions, so there are some interface changes that need to be handled for that.

There are reported several performance optimizations, so this should help wit hthose issues a s well.

Details about changes:

http://www.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES-4.4.x.txt [^]
http://www.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.4.x.txt [^]

**Comment by bjakke** [comment]
The pom.xml defines versions 4.4.4 and 4.5.2 and tests did pass, so closing this. 

I would assume the interface changes were done at some point but the mantis task was not closed. There was a bug in some earlier 4.4.x version that caused the connection to freeze on certain message size, which prevented the update, but it did not happen when testing with the latest available versions during the conversion to maven project.
