### ISSUE TITLE
Constant 200 millisecond waits in service calls with certain condition

### ISSUE THREAD

**Issue by htahvanainen** [OPCFoundation/UA-Java#60]
Seems that Nagle's algorithm causes constant wait times when there's two outgoing messages and one incoming message.

The issue can be reproduced for example with subscriptions. Following message exchange between client and server shows the issue:
1. Publish Request from Client
2. Read Request from Client
3. Read Response from Server

The client application experiences constant wait during the read call. The wait can be platform dependent. On Windows 10 platform the wait is constant 200 milliseconds when the server application is accessed over a network and not on localhost. Subsequent reads operate normally, only the first one after the publish request is affected.

Setting Socket.setTcpNoDelay(true) when the socket is created in the TcpConnection class prevents this behaviour. The Nagle's algorithm probably provides no benefits in the context of the Java Stack but it may cause this kind of drawbacks.

**Comment by bjakke** [comment]
Fixed in referenced commit
