### ISSUE TITLE
Add support for TLS 1.2 with PFS

### ISSUE THREAD

**Issue by jouniaro** [OPCFoundation/UA-Java#61]
Spec Part 7 - v1.03 defines a new Security profile, "TransportSecurity  –  TLS 1.2  with 
PFS"

"This Facet defines a transport security for configurations with high security needs and perfect forward security (PFS). It make s use of TLS 1.2 and uses TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 or 
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"

Support for this should be added to the stack.

**Comment by bjakke** [comment]
Fixed in referenced commit
