### ISSUE TITLE
License texts are different in LICENSE.txt and on official page

### ISSUE THREAD

**Issue by AriSuutariST** [OPCFoundation/UA-Java#63]
License in http://opcfoundation.github.io/UA-Java/ states that RCL license applies to "OPC Foundation Corporate Members". 

License in https://github.com/OPCFoundation/UA-Java/blob/master/LICENSE.txt states that RCL applies to "OPC Foundation members in good-standing".

These sound different to me. To my understanding, the wording in LICENSE.txt allows RCL licensing to OPC foundation end users also.

Which one is correct ?

**Comment by jouniaro** [comment]
To "OPC Foundation Corporate Members" is correct. LICENSE.txt should changed accordingly.

**Comment by AriSuutariST** [comment]
Ok, good to know :-(

**Comment by jouniaro** [comment]
Fine, but let's keep it open until the text has been changed.

**Comment by bjakke** [comment]
Fixed in referenced commit.
