### ISSUE TITLE
ServerEndpoints in CreateSessionResponse needlessly verified

### ISSUE THREAD

**Issue by htahvanainen** [OPCFoundation/UA-Java#67]
The specification regarding Create Session was changed in spec version 1.02. Now the spec says: "It is recommended that Servers only include the endpointUrl, securityMode, securityPolicyUri, userIdentityTokens, transportProfileUri and securityLevel with all other parameters set to null. Only the recommended parameters shall be verified by the client."

At the moment the stack verifies also other parameters. This is unneeded and can cause interop problems with some server applications.

**Comment by bjakke** [comment]
It would seem this is already done in some earlier versions, closing issue.
