### ISSUE TITLE
AccessLevel missing StatusWrite and TimestampWrite fields.

### ISSUE THREAD

**Issue by Gabun** [OPCFoundation/UA-Java#72]
According to OPC UA Part 3 - Address Space Model 1.03 Specification, 5.6.2  Variable NodeClass, Table 8  –  Variable NodeClass. The optional parameter AccessLevel should have  7 fields but the stack enum implementation has only 5, I checked the .NET implementation and the definition of AccessLevels has 8 cases. I don't see the need for 8 cases because case 0 would make the node useless, but maybe there is case where this is required.

Even if the class is optional if added to the stack it should be compliant with the standard.

**Comment by bjakke** [comment]
This is a dublicate of #52 and will be implemented in 1.03.340.2, therefore closing this issue.
