### ISSUE TITLE
Mantis 3735 - handling of unused Variant Type Ids

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#89]
Added rule to UA Part 6:

The Built-in Type Ids 26 through 31 are not currently assigned but may be used in the future. Decoders shall accept these IDs, assume the Value contains a ByteString and pass both onto the application. Encoders shall not use these IDs.

**Comment by bjakke** [comment]
This is defined in the UA 1.04 draft, therefore it should not be implemented at least until the specification version 1.04 is released.

**Comment by bjakke** [comment]
I'm not exactly sure what should be done in this situation if the Array/ArrayDimension bits are set in the EncodingMask, raised https://opcfoundation-onlineapplications.org/mantis/view.php?id=4478 as I see potentially 2 possible ways it could go (array of ByteStrings vs. a single ByteString, althrough an array of ByteStrings would make more sense)
