### ISSUE TITLE
Example Maven project is looking for 1.03.340.0-SNAPSHOT while stack has been incremented to 1.03.341.0-SNAPSHOT 

### ISSUE THREAD

**Issue by justlikeef** [OPCFoundation/UA-Java#90]

**Comment by Lutier2017** [comment]
Click "pom.xml" file on Eclipse "Package Explorer"
   1) In "Overview" TAB, change <Version> from "1.03.340.0-SNAPSHOT" to "1.03.341.0-SNAPSHOT"
   2) In "Dependencies" TAB, Click "opc-ua-stack: 1.03.340.0-SNAPSHOT"
                          2,1) Click "Properties" button
                          2.2) change <Version> from "1.03.340.0-SNAPSHOT" to "1.03.341.0-SNAPSHOT"

**Comment by bjakke** [comment]
Changed dependency version to be ${project.version} and updated samples to same version number as stack.
