### ISSUE TITLE
Build Failures

### ISSUE THREAD

**Issue by rupipal** [OPCFoundation/UA-Java#92]
I git cloned from the github UA-Java repository https://github.com/OPCFoundation/UA-Java to a folder UA-Java.

In the root of UA-Java, I ran

mvn package  
Then, again from the root of UA-Java

mvn install
Finally,

in the examples\basic

mvn package
I got build failures for each of those. The last-parts of outputs are at here https://pastebin.com/Mh3x5hHD.

Could somebody help?
Rupinder

**Comment by jouniaro** [comment]
This is a duplicate of #84 
Please see the instructions in there to skip the tests that are failing in Java 8.
