### ISSUE TITLE
Connection with Sample Client failed Bad_CertificateInvalid

### ISSUE THREAD

**Issue by bastiStern** [OPCFoundation/UA-Java#96]
Hi,

im trying to establish a connection with the sampleClient to an Siemens Simatic S7 - 1500 PLC unit with internal OPC-UA Server. The server is set to None Security and should accept all connections from Clients.

if i run the Sample Client with the given url "opc.tcp://192.168.2.200:4840" i am getting the following exception.

> Exception in thread "main" org.opcfoundation.ua.common.RuntimeServiceResultException: org.opcfoundation.ua.common.ServiceResultException: Bad_CertificateInvalid (code=0x80120000, description="2148663296, java.io.IOException: Duplicate extensions not allowed")
> 	at org.opcfoundation.ua.transport.TransportChannelSettings.getServerCertificate(TransportChannelSettings.java:114)
> 	at org.opcfoundation.ua.transport.tcp.io.TcpConnection.initialize(TcpConnection.java:376)
> 	at org.opcfoundation.ua.transport.tcp.io.SecureChannelTcp.initialize(SecureChannelTcp.java:273)
> 	at org.opcfoundation.ua.transport.tcp.io.SecureChannelTcp.initialize(SecureChannelTcp.java:246)
> 	at org.opcfoundation.ua.application.Client.createSecureChannel(Client.java:640)
> 	at org.opcfoundation.ua.application.Client.createSecureChannel(Client.java:555)
> 	at org.opcfoundation.ua.application.Client.createSessionChannel(Client.java:370)
> 	at org.opcfoundation.ua.application.Client.createSessionChannel(Client.java:345)
> 	at org.opcfoundation.ua.examples.SampleClient.main(SampleClient.java:109)
> Caused by: org.opcfoundation.ua.common.ServiceResultException: Bad_CertificateInvalid (code=0x80120000, description="2148663296, java.io.IOException: Duplicate extensions not allowed")
> 	at org.opcfoundation.ua.transport.security.Cert.<init>(Cert.java:143)
> 	at org.opcfoundation.ua.transport.TransportChannelSettings.getServerCertificate(TransportChannelSettings.java:112)
> 	... 8 more
> 
 
i have a sample Programm in C#/.NET which works fine with this server but i can not manage to connect to it with the Java application.

The client discovers all server endpoints, i even tweaked it as mentioned in another thread to connect to None Security server.

Thank you !

**Comment by jouniaro** [comment]
This is an issue with the Siemens Server, which is using a certificate that is invalid according to the RFC 3280 that specifies the usage of certificates:
https://www.ietf.org/rfc/rfc3280.txt

> 4.2 Certificate Extensions
> …
> A certificate MUST NOT include more than
> one instance of a particular extension.
> …

The standard JDK in Java does not accept these certificates and there is no workaround to enable reading the certificate into a Java application. Unfortunately, .NET and C enable usage of these invalid certificates.
