### ISSUE TITLE
Bug testing : "ServerExample1" and "ClientExample1"

### ISSUE THREAD

**Issue by Lutier2017** [OPCFoundation/UA-Java#97]
I was testing "ServerExample1" and "ClienteExample1"
The test did not work
I got the error "The ArrayDimensions do not match the ArrayLength in total size"

I changed the line 1441 
From : long total = 0;
                          to : long total = 1;
in the class : BynaryDecoder
method       : public Variant getVariant(String fieldName)

And the test worked fine.
Please document this bug.

**Comment by jouniaro** [comment]
Yes, this seems to be incorrect. Thanks for the report.
