### ISSUE TITLE
Bug testing "TestStackExample.java"

### ISSUE THREAD

**Issue by Lutier2017** [OPCFoundation/UA-Java#98]
I was testing "TestStackExample.java"
The test did not work
I got the error :

496  INFO  [main] org.opcfoundation.ua.transport.tcp.io.TcpConnection     - MyComputer/10.53.10.133:6002 Connect failed
org.opcfoundation.ua.common.ServiceResultException: Bad_TcpEndpointUrlInvalid (code=0x80830000, description="Bad_TcpEndpointUrlInvalid (code=0x80830000, description="The Server does not recognize the QueryString specified.")")

==============================

I changed the line 101 :
  From : EndpointDescription[] endpoints = myClient.discoverEndpoints( "opc.tcp://"+hostname+":6002/" ); //51210=Sample Server

  To : EndpointDescription[] endpoints = myClient.discoverEndpoints( "opc.tcp://"+hostname+":6002/UAExample" ); //51210=Sample Server
in the class : TestStackExample
method       : main()

And the test worked fine.
Please document this bug.

**Comment by jouniaro** [comment]
OK, apparently the ServerURI provided as a hint for the .NET SampleServer has been incorrect.

**Comment by bjakke** [comment]
The test request/responses are no longer present in the resources files for UA 1.03, therefore they are not part of the stack anymore, so this class is also removed.
