### ISSUE TITLE
Is there any Clients Examples for HA Read using OPC Foundation SDK

### ISSUE THREAD

**Issue by chandru9050** [OPCFoundation/UA-Java#99]
Is there any Clients Examples for HA Read using OPC Foundation SDK

**Comment by jouniaro** [comment]
No, there are no examples of history read. You will need to use the HistoryReadRequest and provide HistoryReadDetails parameter as defined in the specification. This is not really an SDK, but only the Stack layer, providing the messaging interface. For SDK features, you will need to find an SDK product or write that functionality yourself. Therefore the examples are also limited.

**Comment by chandru9050** [comment]
Hi Thanks for your reply,
